<?php
/*
 * This file belongs to the YIT Framework.
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE (GPL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 */

return array(

    'border-1-top'    => '.woocommerce table.shop_table.order_details tfoot tr:last-child,
                          .woocommerce .cart-collaterals .cart_totals tbody tr.order-total,
                          .yit_post_quote,.yith-ywraq-add-to-quote',

    'border-1-bottom' => '.woocommerce table.shop_table.order_details thead,
                          .woocommerce table.shop_table.order_details tbody,
                          .woocommerce table.shop_table.order_details tfoot tr:last-child,
                          #yith-wcwl-form table.shop_table tbody tr,
                          table.my_account_orders tr.order,
                          .yit_post_quote,.list .yith-ywraq-add-to-quote',

    'border-1-all'    => '.border,
                          input[type="password"],
                          input[type="text"],
                          input[type="email"],
                          input[type="file"],
                          .woocommerce .sbHolder .sbSelector,
                          textarea,
                          #topbar .whislist_nav,
                          #topbar ul.menu > li,
                          #header .yit_cart_widget,
                          #lang_sel ul li a,
                          #wcml_currency_switcher .sbSelector,
                          .general-pagination a,
                          ul.products li.product .product-wrapper .product-actions-wrapper .yith-wcwl-add-to-wishlist,
                          .footer-extra-row,
                          .widget.widget_recent_entries ul li,
                          .widget.widget_recent_comments ul li,
                          .widget_categories ul li,
                          .widget_archive ul li,
                          .widget_meta ul li,
                          .widget_pages ul li,
                          .widget_nav_menu ul li,
                          .widget_search #s,
                          .widget_categories .sbHolder .sbSelector,
                          .widget_archive .sbHolder .sbSelector,
                          .widget_product_categories ul li,
                          .widget.featured-products .flex-direction-nav li a,
                          .widget_categories > ul li i.icon-minus,
                           .widget_categories > ul li i.icon-plus,
                          .widget_product_categories ul.product-categories li i.icon-minus,
                          .widget_product_categories ul.product-categories li i.icon-plus,
                          .widget_product_categories ul.children,
                          .widget_product_categories ul.product-categories > li,
                          .sbHolder .sbOptions,
                          #wp-calendar caption,
                          .toggle,
                          .toggle .toggle-title span.fa.fa-plus.closed,
                          .toggle .toggle-title span.fa.fa-minus.opened,
                          .newsletter_form_email input.email-field,
                          #header-search .autocomplete-suggestions,
                          .filters li a,
                          .arrow:before, .arrow-down:before,
                          .widget.yit-recent-comments div.comment,
                          #faqs-container .faq-wrapper,
                          .single-product.woocommerce div.product div.summary form.cart,
                          #portfolio_content .portfolio_meta:after,
                          #portfolio_content .the_content.with-border:after,
                          .woocommerce .quantity, .woocommerce-page .quantity,
                          .widget.yit_products ul li,
                          .woocommerce .products-slider-wrapper .es-nav-prev span,
                          .woocommerce .products-slider-wrapper .es-nav-next span,
                          nav.woocommerce-pagination .page-numbers,
                          .contact-form li div.input-prepend input[type=text],
                          .contact-form li div.input-prepend input[type=password],
                          .contact-form li div.input-prepend select,
                          .contact-form li.textarea-field div.input-prepend textarea,
                          .vc_row-fluid.with-border .section-background,
                          .categories-slider-wrapper .es-nav-prev span,
                          .categories-slider-wrapper .es-nav-next span,
                          .woocommerce-message,
                          .woocommerce-error,
                          .woocommerce-info,
                          .woocommerce-info:after,
                          .woocommerce form .form-row a.chosen-single,
                          .show-products.show-products-list ul.products li.product .product-wrapper .product-actions-wrapper .yith-wcwl-add-to-wishlist,
                          #page-meta .woocommerce-ordering .sbToggle,
                          .woocommerce form .chosen-container .chosen-drop,
                          #yith-wcwl-form .yith-wcwl-share,
                          .single-product.woocommerce div.product div.images > a img,
                          .single-product.woocommerce div.product div.images .yith_magnifier_zoom_wrap img,
                          .call-to-action-four-container .incipit,
                          .widget.yith-woo-ajax-navigation ul.yith-wcan-label li a,
                          .widget.yith-woo-ajax-navigation ul.yith-wcan-color li a,
                          .widget.yith-woo-ajax-navigation ul.yith-wcan-label li a:hover,
                          .widget.yith-woo-ajax-navigation ul.yith-wcan-label li.chosen a,
                          .widget.woocommerce.widget_layered_nav ul li small.count,
                          .counter,
                          .show-single-product.border-right,
                          .show-single-product.border-left,
                          .quick-view-overlay.product-quick-view .slider-quick-view-container .es-nav-prev,
                          .quick-view-overlay.product-quick-view .slider-quick-view-container .es-nav-next,
                          .st-menu input[type="search"],
                          .testimonials-slider .owl-carousel .owl-controls .owl-nav .owl-prev,
                          .owl-carousel .owl-controls .owl-nav .owl-next,
                          .testimonials-slider .owl-carousel .owl-controls .owl-nav .owl-prev,
                          .owl-carousel .owl-controls .owl-nav .owl-prev,
                          .widget.woocommerce.widget.yith_woocommerce_ajax_search input[type="search"],
                          #searchform #searchsubmit,.woocommerce-product-search input[type="submit"],
                          .woocommerce-checkout .select2-container .select2-choice,.woocommerce-checkout .select2-drop-active,
                          .woocommerce-cart #calc_shipping_country,.woocommerce-cart #calc_shipping_state,.select2-drop.select2-drop-above.select2-drop-active,
                          .select2-dropdown-open.select2-drop-above .select2-choice, .select2-dropdown-open.select2-drop-above .select2-choices,
                          .select2-drop.select2-drop-above.select2-drop-active',

    'border-2-bottom' => '.nav.vertical div.submenu li,
                          .contact-info ul li,
                          .widget.contact-info ul li,
                          #yith-wcwl-form table.shop_table thead,
                          .woocommerce-page table.shop_table.my_account_orders thead,
                          .wpb_content_element.wpb_tabs .lookbook-wrapper,
                          .counter .number:after,
                          .st-menu ul li',

    'border-2-top'    => '#xxxxxxx1234',

    'border-2-all'    => '.border-2,
                          #header.skin2 #header-container .header-wrapper,
                          #nav > div > ul > li.menu-item,
                          #nav > div > ul > li.page_item,
                          #nav > div > ul > li.search-trigger,
          				  .nav div.submenu,
          				  .nav ul.children,
                          #topbar .widget_nav_menu ul.menu ul.sub-menu,
                          #lang_sel li > ul,
                          #wcml_currency_switcher ul li ul,
            			  #header .sbHolder .sbOptions,
            			  #header-search .search_categories,
            			  .teaser-wrapper,
            			  #header .cart_label,
                          #header .widget_shopping_cart .widget_shopping_cart_content h5.list-title,
                          #header .widget_shopping_cart .widget_shopping_cart_content ul.product_list_widget li,
                          #header-search form,
                          #header-search .sbHolder,
                          #header.skin2 #nav,
                          #header-search .shop-by-category > div.submenu-group,
                          #welcome-menu-login .login-box.with_registration .customer-login-box.customer-login-box1,
                          #welcome-menu-login .login-box.with_registration .customer-login-box.customer-login-box2,
                          .slider-container > .container + .shop-by-category > .submenu,
                          .woocommerce ul.product_list_widget li,
                          .slider-container .shop-by-category > div.submenu-group,
                          .slider-container .shop-by-category > div.submenu-group > div.submenu:last-child,
                           #header-search .shop-by-category > div.submenu-group > div.submenu:last-child,
                          .widget.yit_products_category ul.product_list_widget li,
                          .team-author-innerbox,
                          .team-member-social,
                          .widget.yit_portfolio ul li,
                          .widget_nav_menu > div > ul > li > a,
                          .widget_nav_menu > div > ul > li > a:hover,
                          .widget.yit_toggle_menu ul.menu > li,
                          .widget.yit_toggle_menu ul.menu > li.menu-item-has-children > a:before,
                          .testimonial-wrapper,
                          .arrow-left,
                          .arrow-left:before,
                          .price-table,
                          #primary .sidebar-with-border,
                          .products_tabs.tabs-container > ul,
                          .widget.yit-recent-posts .recent-post.compact .hentry-post p.post-date.border-2,
                          .single-product.woocommerce div.product div.summary p.price:after,
                          .single-product.woocommerce div.product div.summary p.price:before,
                          .single-product.woocommerce div.product div.summary #inquiry-form:before,
                          .single-product.woocommerce div.product div.summary #inquiry-form:after,
                          #show-category-product ul.products li a.product-category-link,
                          .categories-slider ul.products li a.product-category-link,
                          #modal-window:after,
                          #modal-window:before,
                          .yit-vertical-megamenu,
                          .yit-vertical-megamenu .nav > ul > li,
                          .show-category .category-thums a,
                          .show-category .category-products a,
                          .yit-vertical-megamenu h3:after,
                          .single-product.woocommerce .woocommerce-tabs ul,
                          .woocommerce.widget.widget_product_search #searchform,.woocommerce.widget.widget_product_search .woocommerce-product-search,
                          .woocommerce.widget.widget_product_search #searchform #s,.woocommerce.widget.widget_product_search .woocommerce-product-search input[type="search"],
                          #primary .widget.newsletter-form.with-border,
                          .widget.yit-recent-comments .the-post .gravatar-wrapper,
                          .faq-icon.fa.fa-plus.closed,#portfolio_big li .info .portfolio_meta:before,
                          #portfolio_big li .info .portfolio_meta:before,
                          .portfolio_lookbook_title:before,
                          #portfolio_content .lookbook-wrapper:not(:last-child):after,
                          .cta-phone,
                          .cta-phone.call-to-action h3:after,
                          .cta-phone.call-to-action .cta-phone-phone:after,
                          .call-three .newsletter-cta-title:after,
                          .blog_section .yit_post_meta_date,
                          .blog-slider .icon-square,
                          .call-to-action-two .call-to-action-two-container,
                          .call-three .newsletter-cta-form-container,
                          .wpb_content_element.wpb_tabs .wpb_tab,
                          .wpb_content_element.wpb_tabs .ui-tabs > ul,
                          .tabs-container ul.tabs,
                          .tabs-container .panel,
						  .products_tabs.tabs-container .panel,
                          .testimonials-slider',

    'border-3-bottom' => '',

    'border-3-top'    => '',

    'border-3-all'    => '',

    'border-4-bottom' => '',

    'border-4-top'    => '',

    'border-4-all'    => '',

    'a-tag-style-1'       => 'a, a:visited, a:link,  .show-category .category-meta a, #welcome-menu-login .lost_password a.signup',

    'a-tag-style-1-hover' => 'a:hover, a:active,
                             .yith-wcwl-add-to-wishlist .yith-wcwl-wishlistaddedbrowse a > span,
                             .yith-wcwl-add-to-wishlist .yith-wcwl-wishlistexistsbrowse a > span,
                              .show-category .category-meta a:hover,
                             .yith-wcwl-add-to-wishlist:hover a > span,
                             #welcome-menu-login .lost_password a.signup,
                             .store-header-wrapper .store-info.skin1 .store-contact span.store-email .store-email-link:hover,
                             .store-header-wrapper .store-info.skin2 .store-contact span.store-email .store-email-link:hover',

    'a-tag-style-2'       => 'a.a-style-2, a.a-style-2:visited, a.a-style-2:link,
                              .widget.featured-products .flex-direction-nav li a:hover,
                              #portfolio_big li .info h3.title a,
                              #primary .widget_nav_menu > div > ul > li > a,
                              #primary .widget_nav_menu > div > ul > li > .sub-menu li a,
                              #portfolio_big li .info .categories a[rel=tag],
                              #portfolio_content a[rel=tag],
                              .widget_archive ul li a,
                              .widget.widget_categories ul li a,
                              .widget.widget_pages ul li a,
                              .widget.widget_meta a,
                              .widget_archive .sbHolder a.sbSelector,
                              .widget_categories .sbHolder a.sbSelector,
                              .widget.woocommerce.widget_product_categories ul.sbOptions a,
                              .widget.yit_toggle_menu ul.menu > li a,
                              #recentcomments a,
                              .categories-slider ul.products li a.product-category-link,
                              .widget_product_categories .product-categories a,
                              .widget_archive ul li .sbHolder a.sbSelector,
                              .categories-slider div.category-name h4,
                              #show-category-product ul.products li .category-count-content .count,
                              .yit-vertical-megamenu .nav > ul > li > a,
                              #reviews #reviews_summary .ywar_filter_reviews,
                              .comments-info-wrapper a,
                              .woocommerce-breadcrumb a,
                              .widget.last-tweets .arrow-left .text a,
                              .woocommerce table.shop_table.order_details tr.order_item td a,
                              .single-product.woocommerce div.product div.summary form.cart .reset_variations,
                              table.shop_table.cart td.product-remove a,
                              #reviews #comments .comment-text a.ywar_votereview,
                              #product-nav > a,
                              .yitpopup_wrapper a.close,
                              div.summary .product_meta span a,
                              .sitemap a,
                              .modal-shortcode .modal .modal-header a,
                              .woocommerce .login-form-checkout .lost_password a,
                              .woocommerce ul.variations .sbOptions li a,
                              .widget.woocommerce.widget_layered_nav ul li a,
                              .widget.yith-woo-ajax-reset-navigation a.yith-wcan-reset-navigation,
                              .widget.yith-woocompare-widget a.clear-all,
                              .widget.yith-woocompare-widget ul.products-list li a.remove,
                              .widget.store-location a,
                              .widget.vendors-list ul li a.vendor-store-url,
                              a.by-vendor-name-link,
                              .wishlist-page-links a,
                              .result-wishlists li.user-wishlist a,
                              .wishlist_manage_table td.wishlist-name a',

    'a-tag-style-2-hover' => 'a.a-style-2:hover, a.a-style-2:active,
                              #header-search .autocomplete-suggestion:hover,
                              #portfolio_big li .info h3.title a:hover, #portfolio_big li .info .categories a[rel=tag]:hover,
                              #portfolio_content a[rel=tag]:hover,
                              .single-product.woocommerce div.woocommerce-tabs ul.tabs li a:hover,
                              .widget.contact-info .contact_info_email:hover p,
                              .contact_info_email:hover p,
                              .comments-info-wrapper a:hover,
                              .yitpopup_wrapper a.close:hover,
                              .modal-shortcode .modal .modal-header a:hover,
                              .tabs-container ul.tabs li.current a, .tabs-container ul.tabs li a:hover,
                              #primary .widget_nav_menu > div > ul > li > a:hover,
                              #primary .widget_nav_menu > div > ul > li > .sub-menu li a:hover,
                              .single-product.woocommerce div.woocommerce-tabs ul.tabs li.active a,
                              .woocommerce form.cart-page .sbHolder ul li a:hover, section.shipping-calculator-form .sbHolder ul li a:hover,
                              #reviews #reviews_summary .ywar_filter_reviews:hover,
                              .woocommerce-breadcrumb a:hover,
                              .widget_archive ul li a.sbSelector:hover,
                              .widget widget_categories ul li a:hover,
                              .lookbook-listed-product .lookbook-information a:hover,
                              .widget.widget_pages ul li a:hover,
                              .widget.yit_products_category ul.product_list_widget a:hover span.product_title,
                              .widget.widget_meta a:hover,
                              .widget_archive .sbHolder a.sbSelector:hover,
                              .widget_categories .sbHolder a.sbSelector:hover,
                              .widget.yit_toggle_menu ul.menu > li > a:hover,
                              .widget.woocommerce.widget_product_categories ul.sbOptions a:hover,
                              .widget_product_categories .product-categories a:hover,
                              .widget.last-tweets .arrow-left .text a:hover,
                              .widget.yit_toggle_menu ul.menu > li a:hover,
                              #show-category-product div.category-name h4:hover,
                              #show-category-product ul.products li .category-count-content .count:hover,
                              .categories-slider ul.products li a.product-category-link:hover,
                              .categories-slider div.category-name h4:hover,
                              .yit-vertical-megamenu .nav > ul > li > a:hover,
                              .comments-info-wrapper a:hover,
                              #recentcomments a:hover,
                              .sitemap a:hover,
                              .widget.yit-recent-posts .recent-post.compact .hentry-post .post-content h3 a.title:hover,
                              .widget.yit-recent-posts .recent-post.compact .hentry-post:hover .post-content h3 a.title,
                              .widget.woocommerce ul.product_list_widget a:hover span.product_title,
                              #page-meta .woocommerce-ordering .sbHolder .sbOptions li a:hover,
                              .woocommerce table.cart td.product-name div.product-name a:hover,
                              .product-meta-wrapper h3.product-name a:hover,
                              .woocommerce table.shop_table.order_details tr.order_item td a:hover,
                              .woocommerce table.shop_table.order_details tfoot tr:last-child th,
                              .woocommerce table.shop_table.order_details tfoot tr:last-child td,
                              .single-product.woocommerce div.product div.summary form.cart .reset_variations:hover,
                              table.shop_table.cart td.product-remove a:hover,
                              .wishlist_table tr td.product-name a:hover,
                              #inquiry-form div.product-inquiry span.inquiry-title:hover,
                              #modal-window .modal-shortcode .modal-opener a:hover,
                              #reviews #comments .comment-text a.ywar_votereview:hover,
                              #reviews #comments .comment-text a.ywar_votereview.ywar_votereview_selected,
                              .single-product.woocommerce div.product div.summary form.cart table.group_table tr td.label a:hover,
                              #product-nav > a:hover,
                              div.summary .product_meta span a:hover,
                              .woocommerce .login-form-checkout .lost_password a:hover,
                              .woocommerce ul.variations .sbOptions li a:hover,
                              .wpb_content_element.wpb_tabs .ui-tabs > ul li a:hover,
                              .wpb_content_element.wpb_tabs .ui-tabs > ul li.ui-state-active a,
                              .widget.woocommerce.widget_layered_nav ul:not( .yith-wcan-label ) li a:hover,
                              .widget.woocommerce.widget_layered_nav ul.yith-wcan-list li.chosen a,
                              .widget.yith-woo-ajax-reset-navigation a.yith-wcan-reset-navigation:hover,
                              .widget.yith-woocompare-widget a.clear-all:hover,
                              .widget.yith-woocompare-widget ul.products-list li a.remove:hover,
                              .widget.store-location a:hover,
                              .widget.vendors-list ul li a.vendor-store-url:hover,
                              a.by-vendor-name-link:hover,
                              .wishlist-page-links a:hover,
                              .result-wishlists li.user-wishlist a:hover,
                              .wishlist_manage_table td.wishlist-name a:hover',

    'p-tag'           => 'p, body, time, dt, dd, td, th, address, .counter .text, ul.short li, .testimonial-wrapper .testimonial-smallquote, .woocommerce .sbHolder .sbSelector,
                            .woocommerce form.cart-page .sbHolder ul li a, section.shipping-calculator-form .sbHolder ul li a,
                            .widget.yith-woo-ajax-navigation ul.yith-wcan-label li a',
);